name: CI/CD for React Vite

on:
  push:
    branches:
      - main

jobs:
  test:
    name: TypeScript Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Install Dependencies
        run: bun i --ci

      - name: Run TypeScript Check
        run: bun run tsc

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test # Ensures the test job completes successfully before running build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Install Dependencies
        run: bun i --ci

      - name: Build Project
        run: bun run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build # Ensures build completes before deploying

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist

      - name: Copy Build to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PATH: ${{ secrets.SERVER_PATH }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Deploy..."
          echo "✅ Deploy Successful "
          # echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          # scp -r -i private_key dist/* $SERVER_USER@$SERVER_HOST:$SERVER_PATH
          # rm -f private_key
