name: Typescript Check

on:
  workflow_call:
    inputs:
      version:
        type: string

jobs:
  typescript-check:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.version }}

      - name: Install Dependencies
        run: bun i --ci

      - name: Run TypeScript Check
        run: bun run tsc
